### ISSUE TITLE
Poetry is failing sometimes, how about adding a requirements.txt

### ISSUE THREAD

**Issue by Deeptanshu-sankhwar** [crestalnetwork/intentkit#463]
While setting up the project using https://github.com/crestalnetwork/intentkit/blob/main/DEVELOPMENT.md, I ran into issues of downloading multiple packages one by one on resultant app crashes. How about having a centralized requirements.txt using `pipreqs` on the root

**Comment by yornfifty** [comment]
out of topic but just in case you wanna try to start it with docker

<details>
<summary><strong>docker-compose.yml</strong></summary>


```
version: '3.8'

x-build: &default-build
  context: .
  dockerfile: Dockerfile

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-intentkit}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  intent-api:
    build: *default-build
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ENV=${ENV:-local}
      - RELEASE=${RELEASE:-local}
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-intentkit}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - CDP_API_KEY_PRIVATE_KEY=${CDP_API_KEY_PRIVATE_KEY}
    ports:
      - "8000:8000"
    command: poetry run uvicorn app.api:app --host 0.0.0.0 --port 8000

  intent-autonomous:
    build: *default-build
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ENV=${ENV:-local}
      - RELEASE=${RELEASE:-local}
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-intentkit}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
      - CDP_API_KEY_PRIVATE_KEY=${CDP_API_KEY_PRIVATE_KEY}
      - INTERNAL_BASE_URL=http://api:8000
    command: poetry run python -m app.autonomous

  # intent-twitter:
  #   build: *default-build
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - ENV=${ENV:-local}
  #     - RELEASE=${RELEASE:-local}
  #     - DB_USERNAME=${POSTGRES_USER:-postgres}
  #     - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_NAME=${POSTGRES_DB:-intentkit}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
  #     - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
  #     - CDP_API_KEY_PRIVATE_KEY=${CDP_API_KEY_PRIVATE_KEY}
  #     - INTERNAL_BASE_URL=http://api:8000
  #   command: poetry run python -m app.twitter

  # intent-tg:
  #   build: *default-build
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - ENV=${ENV:-local}
  #     - RELEASE=${RELEASE:-local}
  #     - DB_USERNAME=${POSTGRES_USER:-postgres}
  #     - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_NAME=${POSTGRES_DB:-intentkit}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
  #     - CDP_API_KEY_NAME=${CDP_API_KEY_NAME}
  #     - CDP_API_KEY_PRIVATE_KEY=${CDP_API_KEY_PRIVATE_KEY}
  #     - INTERNAL_BASE_URL=http://api:8000
  #   command: poetry run python -m app.telegram

volumes:
  postgres_data:

```

</details>

<details>
<summary><strong>Dockerfile</strong></summary>


```
# Use Python slim image as the base
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=2.1.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1

# Add Poetry to PATH
ENV PATH="$POETRY_HOME/bin:$PATH"

# Install system dependencies and Poetry
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        build-essential \
        libpq-dev \
    && curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION \
    && apt-get purge -y --auto-remove curl \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy Poetry configuration files
COPY pyproject.toml poetry.lock* ./

# Install dependencies
RUN poetry install --no-root

# Copy the rest of the application code into the container
COPY . .

RUN poetry install

ARG RELEASE
ENV RELEASE=$RELEASE

# Command to run the application using Poetry
# CMD ["poetry", "run", "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "80"]


```

</details>

run `docker compose up --build -d` everytime you want to rebuild it
